typography_spectrum: 0.060848967637866735
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0.8672294523566961
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.829311614157632
analytics:
  google: null
  facebook: null
  twitter: null
name: WAF
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: |
  dooF 
  dna
   trA eniW
description: Thrive
purpose: []
